### ISSUE TITLE
Fix: re-apply gitter to this repo

### ISSUE THREAD

**Issue by amerlyq** [albfan/ag.vim#52]
There is great problem due to our constant rebase.
Gitter have saved expaired state of our repo and displayed ugly in fork viewer.
Proposition: cancel pull request, delete it completely and then re-apply.
But instead on top of master, need to apply it in between rking and our changes.
In such way gitter will not catch our changes and we could rebase ever our old changes.

**Comment by albfan** [comment]
Ok. Now it is an easy task as there's only a few well-defined feature branches

**Comment by albfan** [comment]
Done. See is a nasty change, update your clone

**Comment by amerlyq** [comment]
Nice. However it hasn't resolved problem with `gitter-badger` fork -- it still shows our old fluffy history.
Rebase is not enough. Need some manipulation with gitter service alone -- as to remove/re-add...
Maybe it will fix it. Reopen?

**Comment by albfan** [comment]
Aha, now I understand you.

https://github.com/gitter-badger/ag.vim/commits/master

but since you are not the owner of gitter-badger, there's nothing you can do. Maybe:

```
$ git remote remove gitter-badger
```

(I say because I can't understand why you see that remote)

What is the program you use to view repo?, I use this:

http://stackoverflow.com/a/22875140/848072

```
$ git logga
$ git loggsa
```

**Comment by amerlyq** [comment]
Oh no, I finally understood where our misunderstanding was.
When I talked about _fork viewer_ I meant online view in github fork browser -- when you clicking on number of right top button `[Fork|218]` and can scroll current state of forks of all people.
You confound it as _repo viewer_ but it's not (I have my own similar, but re-customized aliases).

My reasons to fix its state is due to many people beside me use that _fork viewer_ and `gitter-badger` fork truly stands-out with all that already outdated fluffy stuff.

**Comment by albfan** [comment]
I will ask gitter then. Let's see what they think, but I have read similar issues (about close a fork) and there's no solution.

We are not using almost gitter. I might remove it and see what happens

**Comment by albfan** [comment]
Adding service hook integration to gitter fix this.

Even more, now all activity is monitorized there, show attend gitter should be the only channel needed to keep in sync.

I'm adding travis results to gitter too.

**Comment by albfan** [comment]
travis integration to gitter working too
